MVC_PROJECT_PVIEW/Models/DepartmentModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC_PROJECT_PVIEW.Models
{
    public class DepartmentModel
    {
        public string Dept_Code { get; set; }
        public string Dept_Name { get; set; }
    }
}

MVC_PROJECT_PVIEW/Models/EmployeeModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVC_PROJECT_PVIEW.Models
{
    public class EmployeeModel
    {


        [StringLength(10, ErrorMessage = "Length Should be between 5 to 10", MinimumLength = 5)][Required]
        public string EmpCode { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        [DataType(DataType.Date)][Required]
        public DateTime DateOfBirth { get; set; }
        [Range(2, 8)]
        public int YearsOfExperience { get; set; }
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail is not valid")]
        [Required]
        public string Email { get; set; }
        [RegularExpression(@"\+?\d[\d -]{8,12}\d",ErrorMessage = "Entered phone format is not valid.")][Required]
        public string PhoneNo { get; set; }

    }
}

MVC_PROJECT_PVIEW/Models/EmployeeSearchModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC_PROJECT_PVIEW.Models
{
    public class EmployeeSearchModel
    {
        public string EmpCode { get; set; }
    }
}

MVC_PROJECT_PVIEW/Controllers/EmpByIdController.cs
using System;
using MVC_PROJECT_PVIEW.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_PROJECT_PVIEW.Controllers
{
    public class EmpByIdController : Controller
    {
        // GET: EmpById
        public ActionResult Index()
        {
            return View();
        }

        // GET: EmpById/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: EmpById/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: EmpById/Create
        [HttpPost]
        public ActionResult Create(EmployeeSearchModel model)
        {
            try
            {
                // TODO: Add insert logic here
                TempData["EmpCode"] = model.EmpCode;
                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: EmpById/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: EmpById/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: EmpById/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: EmpById/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MVC_PROJECT_PVIEW/Controllers/EmployeeController.cs
using MVC_PROJECT_PVIEW.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_PROJECT_PVIEW.Controllers
{
    public class EmployeeController : Controller
    {
        List<EmployeeModel> emp = new List<EmployeeModel>()
               {
                   new EmployeeModel{EmpCode= "AAA01",FirstName="Martin",LastName="Shalin",DateOfBirth=DateTime.Now,YearsOfExperience=5,Email="marting.shalin@g.com",PhoneNo="9855234317"},
                   new EmployeeModel{EmpCode= "AAA02",FirstName="Max",LastName="Black",DateOfBirth=DateTime.Now,YearsOfExperience=3,Email="max.black@g.com",PhoneNo="9855761317"},
                   new EmployeeModel{EmpCode= "AAA03",FirstName="John",LastName="Bold",DateOfBirth=DateTime.Now,YearsOfExperience=8,Email="John.Bold @g.com",PhoneNo="8755234317"},
                   new EmployeeModel{EmpCode= "AAA04",FirstName="Maya",LastName="Chain",DateOfBirth=DateTime.Now,YearsOfExperience=4,Email="maya.chain @g.com",PhoneNo="9855238327"},
                   new EmployeeModel{EmpCode= "AAA05",FirstName="William",LastName="Shatner",DateOfBirth=DateTime.Now,YearsOfExperience=5,Email="william.shatner @g.com",PhoneNo="9816934317"}

        };

        // GET: Employee
        public ActionResult Index()
        {

            return View();
        }

        // GET: Employee/Details/5
        public ActionResult Details()
        {

            return View(emp);
        }

        // GET: Employee/Create
        public ActionResult Create()
        {
            return View();
        }


        // POST: Employee/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Employee/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Employee/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Employee/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Employee/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MVC_PROJECT_PVIEW/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_PROJECT_PVIEW.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVC_PROJECT_PVIEW/Views/EmpById/Create.cshtml
@model MVC_PROJECT_PVIEW.Models.EmployeeSearchModel

@{
    ViewBag.Title = "EmpByID";
}

<h2>EmpByID</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EmployeeSearchModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmpCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmpCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmpCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC_PROJECT_PVIEW/Views/Employee/Create.cshtml
@model MVC_PROJECT_PVIEW.Models.EmployeeModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EmployeeModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmpCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmpCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmpCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YearsOfExperience, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YearsOfExperience, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YearsOfExperience, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Search by Id", "Create", "EmpById")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC_PROJECT_PVIEW/Views/Employee/Details.cshtml
@model List<MVC_PROJECT_PVIEW.Models.EmployeeModel>
<h2>Details</h2>


@{
    ViewBag.Title = "Details";
    foreach (var item in Model)
    {
        if (item.EmpCode == Convert.ToString(TempData["EmpCode"]))
        { Html.RenderPartial("EmployeePartial", item); }
    }

}

MVC_PROJECT_PVIEW/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";


}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVC_PROJECT_PVIEW/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVC_PROJECT_PVIEW/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MVC_PROJECT_PVIEW/Views/Shared/EmployeePartial.cshtml
@model MVC_PROJECT_PVIEW.Models.EmployeeModel

<div>
    <h4>EmployeeModel</h4>
    <hr />
    <h5>Employee code : @Model.EmpCode</h5>
    <h5>First Name : @Model.FirstName</h5>
    <h5>Last Name : @Model.LastName</h5>
    <h5>Date of birth : @Model.DateOfBirth</h5>
    <h5>Years of Experience : @Model.YearsOfExperience</h5>
    <h5>Email : @Model.Email</h5>
    <h5>Phone number : @Model.PhoneNo</h5>

</div>

MVC_PROJECT_PVIEW/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Employee", "Create", "Employee")</li>
                    <li>@Html.ActionLink("Employee Detail", "Details", "Employee")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MVC_PROJECT_PVIEW/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <table border="1">
        <tr>
            <td >  <h1> THis is from new layout file</h1></td>
        </tr>
    </table>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Employee", "Employee", "Employee")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>